# Generated by Django 4.2.23 on 2025-07-28 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('restaurant', '음식점'), ('cafe', '카페/디저트')], max_length=20, verbose_name='카테고리')),
                ('subcategory', models.CharField(blank=True, choices=[('korean', '한식'), ('snack', '분식'), ('japanese', '일식'), ('fastfood', '패스트푸드'), ('salad', '샐러드')], max_length=20, null=True, verbose_name='음식 종류')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='store_photo', verbose_name='가게 이미지')),
                ('name', models.CharField(max_length=100, verbose_name='가게 이름')),
                ('rating', models.FloatField(default=0.0, verbose_name='별점')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('congestion', models.CharField(choices=[('low', '여유'), ('medium', '보통'), ('high', '혼잡')], default='low', max_length=10, verbose_name='혼잡도')),
                ('current_customers', models.IntegerField(default=0, verbose_name='현재 손님 수')),
                ('max_customers', models.IntegerField(default=0, verbose_name='최대 수용 인원')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='영업 시작 시간')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='영업 종료 시간')),
                ('break_start_time', models.TimeField(blank=True, null=True, verbose_name='브레이크타임 시작 시간')),
                ('break_end_time', models.TimeField(blank=True, null=True, verbose_name='브레이크타임 종료 시간')),
                ('naver_url', models.URLField(blank=True, null=True, verbose_name='가게 네이버 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveIntegerField(choices=[(1, '1명'), (2, '2명'), (3, '3명'), (4, '4명'), (5, '5명'), (6, '6명 이상')])),
                ('wait_time', models.CharField(choices=[('바로 입장', '바로 입장'), ('10분 이내', '10분 이내'), ('20분 이내', '20분 이내'), ('30분 이내', '30분 이내'), ('1시간 이내', '1시간 이내'), ('2시간 이상', '2시간 이상')], max_length=20)),
                ('congestion', models.CharField(choices=[('여유', '여유'), ('보통', '보통'), ('혼잡', '혼잡')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'store')},
            },
        ),
    ]
