# Generated by Django 4.2.23 on 2025-08-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_subcategory_alter_store_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='naver_url',
        ),
        migrations.AddField(
            model_name='store',
            name='kakao_url',
            field=models.URLField(blank=True, null=True, verbose_name='카카오맵 링크'),
        ),
    ]
