# Generated by Django 4.2.23 on 2025-08-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='back_gate_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='main_gate_distance',
            field=models.IntegerField(default=0),
        ),
    ]
