# Generated by Django 4.2.23 on 2025-08-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_back_gate_distance_store_main_gate_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(blank=True, choices=[('cafe', '카페,디저트'), ('korean', '한식'), ('chinese', '중식'), ('japanese', '일식'), ('fastfood', '패스트푸드'), ('bunsik', '분식'), ('healthy', '건강식'), ('western', '양식'), ('bbq', '고깃집'), ('bar', '주점')], max_length=20, null=True, verbose_name='카테고리'),
        ),
    ]
