# Generated by Django 4.2.23 on 2025-08-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='가게 이미지'),
        ),
    ]
