# Generated by Django 4.2.23 on 2025-08-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_store_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='break_end_time',
        ),
        migrations.RemoveField(
            model_name='store',
            name='break_start_time',
        ),
        migrations.RemoveField(
            model_name='store',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='store',
            name='open_time',
        ),
        migrations.AddField(
            model_name='store',
            name='business_hours',
            field=models.JSONField(blank=True, null=True, verbose_name='요일별 영업/브레이크 타임'),
        ),
    ]
