# Generated by Django 4.2.23 on 2025-08-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_remove_store_break_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='menus',
            field=models.JSONField(blank=True, null=True, verbose_name='대표 메뉴'),
        ),
    ]
