# Generated by Django 4.2.23 on 2025-08-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='mood_tags',
            field=models.JSONField(blank=True, null=True, verbose_name='분위기 태그'),
        ),
    ]
