# Generated by Django 4.2.23 on 2025-08-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='menu_names',
            field=models.TextField(blank=True, null=True, verbose_name='메뉴 이름'),
        ),
    ]
