# Generated by Django 4.2.23 on 2025-08-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_store_mood_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='store',
            name='current_customers',
        ),
        migrations.RemoveField(
            model_name='store',
            name='max_customers',
        ),
        migrations.AddField(
            model_name='store',
            name='google_hourly',
            field=models.JSONField(blank=True, null=True, verbose_name='구글 인기시간대 퍼센트'),
        ),
        migrations.AddField(
            model_name='store',
            name='google_url',
            field=models.URLField(blank=True, null=True, verbose_name='구글맵 링크'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='congestion',
            field=models.CharField(choices=[('low', '여유'), ('medium', '보통'), ('high', '혼잡')], max_length=10),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='wait_time',
            field=models.CharField(choices=[('바로 입장', '바로 입장'), ('10분 이내', '10분 이내'), ('20분 이내', '20분 이내'), ('30분 이내', '30분 이내'), ('1시간 이내', '1시간 이내'), ('1시간 이상', '1시간 이상')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['store', '-created_at'], name='stores_visi_store_i_979cbd_idx'),
        ),
    ]
